### PR TITLE
promise-sequential stops executing promises once one of them is rejected

### LINKED ISSUE #1: promise-sequential should fail after first reject/exception
E.g.:
```javascript
sequential([
  () => Promise.resolve(),

  () => Promise.reject(),

  () => Promise.resolve(),  // should not be resolved!!!!!!  <---------------
]);
```

### PR DESCRIPTION
**Pull request by AntonioRecaldeRusso**
Fixes #1

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -51,4 +51,32 @@ describe('sequentially promises', () => {
...
+      () => updateResolvedPromises('p1'),
+
+      () => Promise.reject(),
+
+      () => updateResolvedPromises('p3'),
+    ];
+
+    Promise.resolve(promiseq(promises))
+    .catch(() => {
+      expect(resolvedPromises).to.deep.equal(expectedResolvedPromises);
```
Comment (AliTajeldin) [inline test/index.js]: wouldn't this still pass with the current error in the code.  That is, at the time this catch block is called, p3 has not executed yet, so the expected output should have matched as well.

**Review by AliTajeldin — CHANGES_REQUESTED** [review]

File: test/index.js (hunk 1 above)
Comment (AntonioRecaldeRusso) [reply test/index.js]: @ You are absolutely right. I applied the fix in f47c74c and I believe now it works as expected.

File: test/index.js [hunk 2]
```diff
@@ -73,9 +73,32 @@ describe('sequentially promises', () => {
 
     Promise.resolve(
       promiseq(promises)
-      /* catching errors will force the .then of the wrapper promise to be
-         called after the last promise is executed */
-      .catch(() => {})
+      .catch(() => {
+        /*
+          This catch block exists in order to force the '.then' of the wrapper promise
```
Comment (AliTajeldin) [inline test/index.js]: There is no way to "force a then block to execute" so this statement is false.
Too long of a description.  Be pithy and get to the point.

**Review by AliTajeldin — CHANGES_REQUESTED** [review]

**Comment by kmannislands** [comment]
The describe text could be more clear for future/outside readers. 

`should not keep running after one of the promises is rejected` is a bit vague IMO. The process should absolutely not stop running. However, the sequential promises should not be executed.

Bonus points for fixing the 'describe' text on the previous (3rd) mocha test as well. `should return 1 as param of catch function` isn't what it's really testing.

**Comment by AntonioRecaldeRusso** [comment]
@AliTajeldin @kmannislands  I added better comments.

**Comment by kmannislands** [comment]
@AntonioRecaldeRusso Length of the comment is comparable to the length of the entire source code.

**Comment by AntonioRecaldeRusso** [comment]
@kmannislands 
Yes. @AliTajeldin said "explain the error really well".
However, I'm down for making it a 2 liner.

**Comment by jacobdr** [comment]
I don’t think that long comments describing a test case are a bad thing... If the issue is that the length obfuscates the problem that might be another thing.

**Comment by AliTajeldin** [comment]
@AntonioRecaldeRusso still too long.  Let's work on that together.

**Comment by AntonioRecaldeRusso** [comment]
@AliTajeldin changes made

File: index.js [hunk 3]
```diff
@@ -25,6 +25,31 @@ module.exports = function (promises) {
...
     })
+    /*
+      The catch below makes sequential halt the execution of promises as soon as the first promise
+      is rejected or an error is thrown.
+
+      Previously, the code used to handle errors the promise sequence within the reduce function,
+      without re-throwing them. This hid the error from the 'reduce' function, which would continue
+      to execute promises as if nothing happened.
+
+      // underneath the hood the code looked like this
```
Comment (AliTajeldin) [inline index.js]: Simplify this to get rid of the reduce and show the final promise chain. Given a promise sequence of `[ () => p1, ... ]`, we would generate `p1.catch().p2.catch().p3.catch()` which is why we would continue to execute.

File: index.js [hunk 4]
```diff
@@ -25,6 +25,31 @@ module.exports = function (promises) {
...
+      [ () => p1.catch()
+        () => p2.catch()
+        () => p3.catch()
+      ].reduce(...)
+        .then()
+
+      Instead, now as soon as an error is thrown, the reduce function is halted and an outer catch
+      block handles the error. E.g.
+
+      [ () => p1
```
Comment (AliTajeldin) [inline index.js]: simplify this also as `p1.p2.p3.catch()`

File: test/index.js [hunk 5]
```diff
@@ -73,36 +84,9 @@ describe('sequentially promises', () => {
...
-
-          [ () => updateResolvedPromises('p1')
-            () => Promise.reject())
-            () => .then(updateResolvedPromises('p3'))
-          ].reduce(...)
-              .then()
-              .catch(() => reject())  <-- after first reject, reduce will stop execution
-        */
-      })
+      /* The catch below prevents the '.catch' of the outer promise, thus the next '.then' will
```
Comment (AliTajeldin) [inline test/index.js]: it actually does not "prevent" the catch of the outer promise.  We are depending on that to run so that the outer promise is rejected.

**Review by AliTajeldin — CHANGES_REQUESTED** [review]

**Comment by AntonioRecaldeRusso** [comment]
@AliTajeldin changes made

**Comment by AntonioRecaldeRusso** [comment]
Improved the code a little bit making it more simple. There were a lot of unnecessary wrapper promises.
@AliTajeldin please re-review

**Comment by kmannislands** [comment]
Looks much cleaner.
Why was the timeout for mocha changed to be lower?
Only other thing I can think to test is replacing `Promise.reject()` with `Promise.resolve((() => { throw new Error() })())` or something like that. I suppose I trust node to treat the two (almost) the same.

File: index.js [hunk 6]
```diff
@@ -5,42 +5,19 @@ module.exports = function (promises) {
...
+    return previousPromise
+      .then(function (result) {
+        if (count++ !== 0) results = results.concat(result);
+        return currentPromise(result, results, count);
+      })
+  }
 
-  });
+  return promises
+  // reduce() concatenates the promises. E.g. p1.then(p2.then(p3.then()))
```
Comment (AliTajeldin) [inline index.js]: p1.then(p2).then(p3)

**Review by AliTajeldin — CHANGES_REQUESTED** [review]
Looks really good with the removal of the outer promise.  Minor comment change.

**Comment by AntonioRecaldeRusso** [comment]
@kmannislands 
I set it back to the original value

**Review by AliTajeldin — APPROVED** [review]
